POST /webhooks HTTP/1.1
accept: */*
connection: close
content-type: application/json
user-agent: GitHub-Hookshot/6c41911
x-github-delivery: 871ac330-cc0b-11f0-9e97-ffaea3dfc6b5
x-github-enterprise-host: github.com
x-github-enterprise-version: 3.17.7
x-github-event: pull_request
x-github-hook-id: 2
x-github-hook-installation-target-id: 17
x-github-hook-installation-target-type: organization

{
    "pull_request": {
        "url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/pulls/8885",
        "id": 5511394,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NTUxMTM5NA==",
        "html_url": "https://github.example.com/corp/rgt-payrules-copy/pull/8885",
        "diff_url": "https://github.example.com/corp/rgt-payrules-copy/pull/8885.diff",
        "patch_url": "https://github.example.com/corp/rgt-payrules-copy/pull/8885.patch",
        "issue_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues/8885",
        "number": 8885,
        "state": "open",
        "locked": false,
        "title": "LargeRepoMockTestDraft",
        "user": {
            "login": "rgt-github-integration[bot]",
            "id": 10937,
            "node_id": "MDM6Qm90MTA5Mzc=",
            "avatar_url": "https://github.example.com/avatars/u/17?",
            "gravatar_id": "",
            "url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D",
            "html_url": "https://github.example.com/github-apps/rgt-github-integration",
            "followers_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/followers",
            "following_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/following{/other_user}",
            "gists_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/subscriptions",
            "organizations_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/orgs",
            "repos_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/repos",
            "events_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/received_events",
            "type": "Bot",
            "user_view_type": "public",
            "site_admin": false
        },
        "body": "Draft created by e2e test\n\nView changes: https://summit.test.example.net/rgt-playwright-tests/payrules-prod-copy-jenkins-12408-1764301002048/changes/cmVmcy9oZWFkcy9mZWF0dXJlLzIwMjUtMTEtMjhfMDMtMzYtNTkvTGFyZ2VSZXBvTW9ja1Rlc3REcmFmdA==?item=rules%2Fpayments%2FCvvRequirement.json",
        "created_at": "2025-11-28T03:37:12Z",
        "updated_at": "2025-11-28T03:37:13Z",
        "closed_at": null,
        "merged_at": null,
        "merge_commit_sha": null,
        "assignee": null,
        "assignees": [],
        "requested_reviewers": [
            {
                "login": "rpilani",
                "id": 3653,
                "node_id": "MDQ6VXNlcjM2NTM=",
                "avatar_url": "https://github.example.com/avatars/u/3653?",
                "gravatar_id": "",
                "url": "https://github.example.com/api/v3/users/rpilani",
                "html_url": "https://github.example.com/rpilani",
                "followers_url": "https://github.example.com/api/v3/users/rpilani/followers",
                "following_url": "https://github.example.com/api/v3/users/rpilani/following{/other_user}",
                "gists_url": "https://github.example.com/api/v3/users/rpilani/gists{/gist_id}",
                "starred_url": "https://github.example.com/api/v3/users/rpilani/starred{/owner}{/repo}",
                "subscriptions_url": "https://github.example.com/api/v3/users/rpilani/subscriptions",
                "organizations_url": "https://github.example.com/api/v3/users/rpilani/orgs",
                "repos_url": "https://github.example.com/api/v3/users/rpilani/repos",
                "events_url": "https://github.example.com/api/v3/users/rpilani/events{/privacy}",
                "received_events_url": "https://github.example.com/api/v3/users/rpilani/received_events",
                "type": "User",
                "user_view_type": "public",
                "site_admin": false
            }
        ],
        "requested_teams": [],
        "labels": [],
        "milestone": null,
        "draft": false,
        "commits_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/pulls/8885/commits",
        "review_comments_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/pulls/8885/comments",
        "review_comment_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/pulls/comments{/number}",
        "comments_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues/8885/comments",
        "statuses_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/statuses/0235962aace653bbc2fbaa27a56fc89677d2780a",
        "head": {
            "label": "corp:feature/2025-11-28_03-36-59/LargeRepoMockTestDraft",
            "ref": "feature/2025-11-28_03-36-59/LargeRepoMockTestDraft",
            "sha": "0235962aace653bbc2fbaa27a56fc89677d2780a",
            "user": {
                "login": "corp",
                "id": 17,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjE3",
                "avatar_url": "https://github.example.com/avatars/u/17?",
                "gravatar_id": "",
                "url": "https://github.example.com/api/v3/users/corp",
                "html_url": "https://github.example.com/corp",
                "followers_url": "https://github.example.com/api/v3/users/corp/followers",
                "following_url": "https://github.example.com/api/v3/users/corp/following{/other_user}",
                "gists_url": "https://github.example.com/api/v3/users/corp/gists{/gist_id}",
                "starred_url": "https://github.example.com/api/v3/users/corp/starred{/owner}{/repo}",
                "subscriptions_url": "https://github.example.com/api/v3/users/corp/subscriptions",
                "organizations_url": "https://github.example.com/api/v3/users/corp/orgs",
                "repos_url": "https://github.example.com/api/v3/users/corp/repos",
                "events_url": "https://github.example.com/api/v3/users/corp/events{/privacy}",
                "received_events_url": "https://github.example.com/api/v3/users/corp/received_events",
                "type": "Organization",
                "user_view_type": "public",
                "site_admin": false
            },
            "repo": {
                "id": 38814,
                "node_id": "MDEwOlJlcG9zaXRvcnkzODgxNA==",
                "name": "rgt-payrules-copy",
                "full_name": "corp/rgt-payrules-copy",
                "private": true,
                "owner": {
                    "login": "corp",
                    "id": 17,
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjE3",
                    "avatar_url": "https://github.example.com/avatars/u/17?",
                    "gravatar_id": "",
                    "url": "https://github.example.com/api/v3/users/corp",
                    "html_url": "https://github.example.com/corp",
                    "followers_url": "https://github.example.com/api/v3/users/corp/followers",
                    "following_url": "https://github.example.com/api/v3/users/corp/following{/other_user}",
                    "gists_url": "https://github.example.com/api/v3/users/corp/gists{/gist_id}",
                    "starred_url": "https://github.example.com/api/v3/users/corp/starred{/owner}{/repo}",
                    "subscriptions_url": "https://github.example.com/api/v3/users/corp/subscriptions",
                    "organizations_url": "https://github.example.com/api/v3/users/corp/orgs",
                    "repos_url": "https://github.example.com/api/v3/users/corp/repos",
                    "events_url": "https://github.example.com/api/v3/users/corp/events{/privacy}",
                    "received_events_url": "https://github.example.com/api/v3/users/corp/received_events",
                    "type": "Organization",
                    "user_view_type": "public",
                    "site_admin": false
                },
                "html_url": "https://github.example.com/corp/rgt-payrules-copy",
                "description": "Copy repo of pay-payrules for our own testing",
                "fork": false,
                "url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy",
                "forks_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/forks",
                "keys_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/keys{/key_id}",
                "collaborators_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/collaborators{/collaborator}",
                "teams_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/teams",
                "hooks_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/hooks",
                "issue_events_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues/events{/number}",
                "events_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/events",
                "assignees_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/assignees{/user}",
                "branches_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/branches{/branch}",
                "tags_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/tags",
                "blobs_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/blobs{/sha}",
                "git_tags_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/tags{/sha}",
                "git_refs_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/refs{/sha}",
                "trees_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/trees{/sha}",
                "statuses_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/statuses/{sha}",
                "languages_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/languages",
                "stargazers_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/stargazers",
                "contributors_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/contributors",
                "subscribers_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/subscribers",
                "subscription_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/subscription",
                "commits_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/commits{/sha}",
                "git_commits_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/commits{/sha}",
                "comments_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/comments{/number}",
                "issue_comment_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues/comments{/number}",
                "contents_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/contents/{+path}",
                "compare_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/compare/{base}...{head}",
                "merges_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/merges",
                "archive_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/{archive_format}{/ref}",
                "downloads_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/downloads",
                "issues_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues{/number}",
                "pulls_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/pulls{/number}",
                "milestones_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/milestones{/number}",
                "notifications_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/notifications{?since,all,participating}",
                "labels_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/labels{/name}",
                "releases_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/releases{/id}",
                "deployments_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/deployments",
                "created_at": "2024-09-26T21:06:11Z",
                "updated_at": "2024-09-26T21:23:37Z",
                "pushed_at": "2025-11-28T03:37:06Z",
                "git_url": "git://github.example.com/corp/rgt-payrules-copy.git",
                "ssh_url": "git@github.example.com:corp/rgt-payrules-copy.git",
                "clone_url": "https://github.example.com/corp/rgt-payrules-copy.git",
                "svn_url": "https://github.example.com/corp/rgt-payrules-copy",
                "homepage": null,
                "size": 5436,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": "JavaScript",
                "has_issues": true,
                "has_projects": false,
                "has_downloads": true,
                "has_wiki": false,
                "has_pages": false,
                "has_discussions": false,
                "forks_count": 1,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 97,
                "license": null,
                "allow_forking": true,
                "is_template": false,
                "web_commit_signoff_required": false,
                "topics": [
                    "rgt"
                ],
                "visibility": "private",
                "forks": 1,
                "open_issues": 97,
                "watchers": 0,
                "default_branch": "main",
                "allow_squash_merge": false,
                "allow_merge_commit": true,
                "allow_rebase_merge": false,
                "allow_auto_merge": true,
                "delete_branch_on_merge": true,
                "allow_update_branch": false,
                "use_squash_pr_title_as_default": false,
                "squash_merge_commit_message": "COMMIT_MESSAGES",
                "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
                "merge_commit_message": "BLANK",
                "merge_commit_title": "PR_TITLE"
            }
        },
        "base": {
            "label": "corp:main",
            "ref": "main",
            "sha": "bd24a04e30af483e13b231087d8cc54d4d97558f",
            "user": {
                "login": "corp",
                "id": 17,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjE3",
                "avatar_url": "https://github.example.com/avatars/u/17?",
                "gravatar_id": "",
                "url": "https://github.example.com/api/v3/users/corp",
                "html_url": "https://github.example.com/corp",
                "followers_url": "https://github.example.com/api/v3/users/corp/followers",
                "following_url": "https://github.example.com/api/v3/users/corp/following{/other_user}",
                "gists_url": "https://github.example.com/api/v3/users/corp/gists{/gist_id}",
                "starred_url": "https://github.example.com/api/v3/users/corp/starred{/owner}{/repo}",
                "subscriptions_url": "https://github.example.com/api/v3/users/corp/subscriptions",
                "organizations_url": "https://github.example.com/api/v3/users/corp/orgs",
                "repos_url": "https://github.example.com/api/v3/users/corp/repos",
                "events_url": "https://github.example.com/api/v3/users/corp/events{/privacy}",
                "received_events_url": "https://github.example.com/api/v3/users/corp/received_events",
                "type": "Organization",
                "user_view_type": "public",
                "site_admin": false
            },
            "repo": {
                "id": 38814,
                "node_id": "MDEwOlJlcG9zaXRvcnkzODgxNA==",
                "name": "rgt-payrules-copy",
                "full_name": "corp/rgt-payrules-copy",
                "private": true,
                "owner": {
                    "login": "corp",
                    "id": 17,
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjE3",
                    "avatar_url": "https://github.example.com/avatars/u/17?",
                    "gravatar_id": "",
                    "url": "https://github.example.com/api/v3/users/corp",
                    "html_url": "https://github.example.com/corp",
                    "followers_url": "https://github.example.com/api/v3/users/corp/followers",
                    "following_url": "https://github.example.com/api/v3/users/corp/following{/other_user}",
                    "gists_url": "https://github.example.com/api/v3/users/corp/gists{/gist_id}",
                    "starred_url": "https://github.example.com/api/v3/users/corp/starred{/owner}{/repo}",
                    "subscriptions_url": "https://github.example.com/api/v3/users/corp/subscriptions",
                    "organizations_url": "https://github.example.com/api/v3/users/corp/orgs",
                    "repos_url": "https://github.example.com/api/v3/users/corp/repos",
                    "events_url": "https://github.example.com/api/v3/users/corp/events{/privacy}",
                    "received_events_url": "https://github.example.com/api/v3/users/corp/received_events",
                    "type": "Organization",
                    "user_view_type": "public",
                    "site_admin": false
                },
                "html_url": "https://github.example.com/corp/rgt-payrules-copy",
                "description": "Copy repo of pay-payrules for our own testing",
                "fork": false,
                "url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy",
                "forks_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/forks",
                "keys_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/keys{/key_id}",
                "collaborators_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/collaborators{/collaborator}",
                "teams_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/teams",
                "hooks_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/hooks",
                "issue_events_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues/events{/number}",
                "events_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/events",
                "assignees_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/assignees{/user}",
                "branches_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/branches{/branch}",
                "tags_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/tags",
                "blobs_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/blobs{/sha}",
                "git_tags_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/tags{/sha}",
                "git_refs_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/refs{/sha}",
                "trees_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/trees{/sha}",
                "statuses_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/statuses/{sha}",
                "languages_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/languages",
                "stargazers_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/stargazers",
                "contributors_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/contributors",
                "subscribers_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/subscribers",
                "subscription_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/subscription",
                "commits_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/commits{/sha}",
                "git_commits_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/commits{/sha}",
                "comments_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/comments{/number}",
                "issue_comment_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues/comments{/number}",
                "contents_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/contents/{+path}",
                "compare_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/compare/{base}...{head}",
                "merges_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/merges",
                "archive_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/{archive_format}{/ref}",
                "downloads_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/downloads",
                "issues_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues{/number}",
                "pulls_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/pulls{/number}",
                "milestones_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/milestones{/number}",
                "notifications_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/notifications{?since,all,participating}",
                "labels_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/labels{/name}",
                "releases_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/releases{/id}",
                "deployments_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/deployments",
                "created_at": "2024-09-26T21:06:11Z",
                "updated_at": "2024-09-26T21:23:37Z",
                "pushed_at": "2025-11-28T03:37:06Z",
                "git_url": "git://github.example.com/corp/rgt-payrules-copy.git",
                "ssh_url": "git@github.example.com:corp/rgt-payrules-copy.git",
                "clone_url": "https://github.example.com/corp/rgt-payrules-copy.git",
                "svn_url": "https://github.example.com/corp/rgt-payrules-copy",
                "homepage": null,
                "size": 5436,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": "JavaScript",
                "has_issues": true,
                "has_projects": false,
                "has_downloads": true,
                "has_wiki": false,
                "has_pages": false,
                "has_discussions": false,
                "forks_count": 1,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 97,
                "license": null,
                "allow_forking": true,
                "is_template": false,
                "web_commit_signoff_required": false,
                "topics": [
                    "rgt"
                ],
                "visibility": "private",
                "forks": 1,
                "open_issues": 97,
                "watchers": 0,
                "default_branch": "main",
                "allow_squash_merge": false,
                "allow_merge_commit": true,
                "allow_rebase_merge": false,
                "allow_auto_merge": true,
                "delete_branch_on_merge": true,
                "allow_update_branch": false,
                "use_squash_pr_title_as_default": false,
                "squash_merge_commit_message": "COMMIT_MESSAGES",
                "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
                "merge_commit_message": "BLANK",
                "merge_commit_title": "PR_TITLE"
            }
        },
        "_links": {
            "self": {
                "href": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/pulls/8885"
            },
            "html": {
                "href": "https://github.example.com/corp/rgt-payrules-copy/pull/8885"
            },
            "issue": {
                "href": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues/8885"
            },
            "comments": {
                "href": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues/8885/comments"
            },
            "review_comments": {
                "href": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/pulls/8885/comments"
            },
            "review_comment": {
                "href": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/pulls/comments{/number}"
            },
            "commits": {
                "href": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/pulls/8885/commits"
            },
            "statuses": {
                "href": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/statuses/0235962aace653bbc2fbaa27a56fc89677d2780a"
            }
        },
        "author_association": "NONE",
        "auto_merge": null,
        "active_lock_reason": null,
        "merged": false,
        "mergeable": null,
        "rebaseable": null,
        "mergeable_state": "unknown",
        "merged_by": null,
        "comments": 0,
        "review_comments": 0,
        "maintainer_can_modify": false,
        "commits": 1,
        "additions": 1,
        "deletions": 0,
        "changed_files": 1
    },
    "enterprise": {
        "id": 1,
        "slug": "example",
        "name": "Example",
        "node_id": "MDEwOkVudGVycHJpc2Ux",
        "avatar_url": "https://github.example.com/avatars/b/1?",
        "description": "",
        "website_url": "",
        "html_url": "https://github.example.com/enterprises/example",
        "created_at": "2023-10-12T18:17:01Z",
        "updated_at": "2024-12-11T16:47:46Z"
    },
    "requested_reviewer": {
        "login": "rpilani",
        "id": 3653,
        "node_id": "MDQ6VXNlcjM2NTM=",
        "avatar_url": "https://github.example.com/avatars/u/3653?",
        "gravatar_id": "",
        "url": "https://github.example.com/api/v3/users/rpilani",
        "html_url": "https://github.example.com/rpilani",
        "followers_url": "https://github.example.com/api/v3/users/rpilani/followers",
        "following_url": "https://github.example.com/api/v3/users/rpilani/following{/other_user}",
        "gists_url": "https://github.example.com/api/v3/users/rpilani/gists{/gist_id}",
        "starred_url": "https://github.example.com/api/v3/users/rpilani/starred{/owner}{/repo}",
        "subscriptions_url": "https://github.example.com/api/v3/users/rpilani/subscriptions",
        "organizations_url": "https://github.example.com/api/v3/users/rpilani/orgs",
        "repos_url": "https://github.example.com/api/v3/users/rpilani/repos",
        "events_url": "https://github.example.com/api/v3/users/rpilani/events{/privacy}",
        "received_events_url": "https://github.example.com/api/v3/users/rpilani/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
    },
    "repository": {
        "id": 38814,
        "node_id": "MDEwOlJlcG9zaXRvcnkzODgxNA==",
        "name": "rgt-payrules-copy",
        "full_name": "corp/rgt-payrules-copy",
        "private": true,
        "owner": {
            "login": "corp",
            "id": 17,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjE3",
            "avatar_url": "https://github.example.com/avatars/u/17?",
            "gravatar_id": "",
            "url": "https://github.example.com/api/v3/users/corp",
            "html_url": "https://github.example.com/corp",
            "followers_url": "https://github.example.com/api/v3/users/corp/followers",
            "following_url": "https://github.example.com/api/v3/users/corp/following{/other_user}",
            "gists_url": "https://github.example.com/api/v3/users/corp/gists{/gist_id}",
            "starred_url": "https://github.example.com/api/v3/users/corp/starred{/owner}{/repo}",
            "subscriptions_url": "https://github.example.com/api/v3/users/corp/subscriptions",
            "organizations_url": "https://github.example.com/api/v3/users/corp/orgs",
            "repos_url": "https://github.example.com/api/v3/users/corp/repos",
            "events_url": "https://github.example.com/api/v3/users/corp/events{/privacy}",
            "received_events_url": "https://github.example.com/api/v3/users/corp/received_events",
            "type": "Organization",
            "user_view_type": "public",
            "site_admin": false
        },
        "html_url": "https://github.example.com/corp/rgt-payrules-copy",
        "description": "Copy repo of pay-payrules for our own testing",
        "fork": false,
        "url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy",
        "forks_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/forks",
        "keys_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/keys{/key_id}",
        "collaborators_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/collaborators{/collaborator}",
        "teams_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/teams",
        "hooks_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/hooks",
        "issue_events_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues/events{/number}",
        "events_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/events",
        "assignees_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/assignees{/user}",
        "branches_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/branches{/branch}",
        "tags_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/tags",
        "blobs_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/blobs{/sha}",
        "git_tags_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/tags{/sha}",
        "git_refs_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/refs{/sha}",
        "trees_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/trees{/sha}",
        "statuses_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/statuses/{sha}",
        "languages_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/languages",
        "stargazers_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/stargazers",
        "contributors_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/contributors",
        "subscribers_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/subscribers",
        "subscription_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/subscription",
        "commits_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/commits{/sha}",
        "git_commits_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/git/commits{/sha}",
        "comments_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/comments{/number}",
        "issue_comment_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues/comments{/number}",
        "contents_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/contents/{+path}",
        "compare_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/compare/{base}...{head}",
        "merges_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/merges",
        "archive_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/{archive_format}{/ref}",
        "downloads_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/downloads",
        "issues_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/issues{/number}",
        "pulls_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/pulls{/number}",
        "milestones_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/milestones{/number}",
        "notifications_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/notifications{?since,all,participating}",
        "labels_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/labels{/name}",
        "releases_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/releases{/id}",
        "deployments_url": "https://github.example.com/api/v3/repos/corp/rgt-payrules-copy/deployments",
        "created_at": "2024-09-26T21:06:11Z",
        "updated_at": "2024-09-26T21:23:37Z",
        "pushed_at": "2025-11-28T03:37:06Z",
        "git_url": "git://github.example.com/corp/rgt-payrules-copy.git",
        "ssh_url": "git@github.example.com:corp/rgt-payrules-copy.git",
        "clone_url": "https://github.example.com/corp/rgt-payrules-copy.git",
        "svn_url": "https://github.example.com/corp/rgt-payrules-copy",
        "homepage": null,
        "size": 5436,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 1,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 97,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "rgt"
        ],
        "visibility": "private",
        "forks": 1,
        "open_issues": 97,
        "watchers": 0,
        "default_branch": "main"
    },
    "number": 8885,
    "sender": {
        "login": "rgt-github-integration[bot]",
        "id": 10937,
        "node_id": "MDM6Qm90MTA5Mzc=",
        "avatar_url": "https://github.example.com/avatars/u/17?",
        "gravatar_id": "",
        "url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D",
        "html_url": "https://github.example.com/github-apps/rgt-github-integration",
        "followers_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/followers",
        "following_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/following{/other_user}",
        "gists_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/gists{/gist_id}",
        "starred_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/starred{/owner}{/repo}",
        "subscriptions_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/subscriptions",
        "organizations_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/orgs",
        "repos_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/repos",
        "events_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/events{/privacy}",
        "received_events_url": "https://github.example.com/api/v3/users/rgt-github-integration%5Bbot%5D/received_events",
        "type": "Bot",
        "user_view_type": "public",
        "site_admin": false
    },
    "organization": {
        "login": "corp",
        "id": 17,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjE3",
        "url": "https://github.example.com/api/v3/orgs/corp",
        "repos_url": "https://github.example.com/api/v3/orgs/corp/repos",
        "events_url": "https://github.example.com/api/v3/orgs/corp/events",
        "hooks_url": "https://github.example.com/api/v3/orgs/corp/hooks",
        "issues_url": "https://github.example.com/api/v3/orgs/corp/issues",
        "members_url": "https://github.example.com/api/v3/orgs/corp/members{/member}",
        "public_members_url": "https://github.example.com/api/v3/orgs/corp/public_members{/member}",
        "avatar_url": "https://github.example.com/avatars/u/17?",
        "description": ""
    },
    "action": "review_requested"
}