POST /webhooks HTTP/1.1
accept: */*
b3: 679cb2da8e1be1fb5b11b287b5791ccf-8a0a9d393d7ead08-0
connection: close
content-type: application/json
host: githubhookreceiver.prod.netflix.net
user-agent: GitHub-Hookshot/6c41911
x-github-delivery: e476b170-dfc5-11ef-97ba-e837f5578242
x-github-enterprise-host: github.netflix.net
x-github-enterprise-version: 3.13.7
x-github-event: branch_protection_rule
x-github-hook-id: 2
x-github-hook-installation-target-id: 17
x-github-hook-installation-target-type: organization

{
    "action": "edited",
    "rule": {
        "id": 13110,
        "repository_id": 18022,
        "name": "master",
        "created_at": "2024-07-15T17:20:53.000Z",
        "updated_at": "2024-07-15T17:20:53.000Z",
        "pull_request_reviews_enforcement_level": "non_admins",
        "required_approving_review_count": 0,
        "dismiss_stale_reviews_on_push": false,
        "require_code_owner_review": false,
        "authorized_dismissal_actors_only": false,
        "ignore_approvals_from_contributors": false,
        "required_status_checks": [
            "mce/COSMOS-cosmos-media-commons-release"
        ],
        "required_status_checks_enforcement_level": "non_admins",
        "strict_required_status_checks_policy": false,
        "signature_requirement_enforcement_level": "off",
        "linear_history_requirement_enforcement_level": "off",
        "admin_enforced": false,
        "create_protected": false,
        "allow_force_pushes_enforcement_level": "off",
        "allow_deletions_enforcement_level": "off",
        "merge_queue_enforcement_level": "off",
        "required_deployments_enforcement_level": "off",
        "required_conversation_resolution_level": "off",
        "authorized_actors_only": false,
        "authorized_actor_names": [],
        "require_last_push_approval": false
    },
    "changes": {
        "authorized_dismissal_actors_only": {
            "from": null
        }
    },
    "repository": {
        "id": 18022,
        "node_id": "MDEwOlJlcG9zaXRvcnkxODAyMg==",
        "name": "cosmos-cosmos-media-commons",
        "full_name": "corp/cosmos-cosmos-media-commons",
        "private": true,
        "owner": {
            "login": "corp",
            "id": 17,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjE3",
            "avatar_url": "https://github.netflix.net/avatars/u/17?",
            "gravatar_id": "",
            "url": "https://github.netflix.net/api/v3/users/corp",
            "html_url": "https://github.netflix.net/corp",
            "followers_url": "https://github.netflix.net/api/v3/users/corp/followers",
            "following_url": "https://github.netflix.net/api/v3/users/corp/following{/other_user}",
            "gists_url": "https://github.netflix.net/api/v3/users/corp/gists{/gist_id}",
            "starred_url": "https://github.netflix.net/api/v3/users/corp/starred{/owner}{/repo}",
            "subscriptions_url": "https://github.netflix.net/api/v3/users/corp/subscriptions",
            "organizations_url": "https://github.netflix.net/api/v3/users/corp/orgs",
            "repos_url": "https://github.netflix.net/api/v3/users/corp/repos",
            "events_url": "https://github.netflix.net/api/v3/users/corp/events{/privacy}",
            "received_events_url": "https://github.netflix.net/api/v3/users/corp/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "html_url": "https://github.netflix.net/corp/cosmos-cosmos-media-commons",
        "description": null,
        "fork": false,
        "url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons",
        "forks_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/forks",
        "keys_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/keys{/key_id}",
        "collaborators_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/collaborators{/collaborator}",
        "teams_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/teams",
        "hooks_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/hooks",
        "issue_events_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/issues/events{/number}",
        "events_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/events",
        "assignees_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/assignees{/user}",
        "branches_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/branches{/branch}",
        "tags_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/tags",
        "blobs_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/git/blobs{/sha}",
        "git_tags_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/git/tags{/sha}",
        "git_refs_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/git/refs{/sha}",
        "trees_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/git/trees{/sha}",
        "statuses_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/statuses/{sha}",
        "languages_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/languages",
        "stargazers_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/stargazers",
        "contributors_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/contributors",
        "subscribers_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/subscribers",
        "subscription_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/subscription",
        "commits_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/commits{/sha}",
        "git_commits_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/git/commits{/sha}",
        "comments_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/comments{/number}",
        "issue_comment_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/issues/comments{/number}",
        "contents_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/contents/{+path}",
        "compare_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/compare/{base}...{head}",
        "merges_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/merges",
        "archive_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/{archive_format}{/ref}",
        "downloads_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/downloads",
        "issues_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/issues{/number}",
        "pulls_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/pulls{/number}",
        "milestones_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/milestones{/number}",
        "notifications_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/notifications{?since,all,participating}",
        "labels_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/labels{/name}",
        "releases_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/releases{/id}",
        "deployments_url": "https://github.netflix.net/api/v3/repos/corp/cosmos-cosmos-media-commons/deployments",
        "created_at": "2024-07-15T17:08:29Z",
        "updated_at": "2024-07-15T17:20:51Z",
        "pushed_at": "2025-01-30T12:18:16Z",
        "git_url": "git://github.netflix.net/corp/cosmos-cosmos-media-commons.git",
        "ssh_url": "git@github.netflix.net:corp/cosmos-cosmos-media-commons.git",
        "clone_url": "https://github.netflix.net/corp/cosmos-cosmos-media-commons.git",
        "svn_url": "https://github.netflix.net/corp/cosmos-cosmos-media-commons",
        "homepage": null,
        "size": 6471,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Java",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": false,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 2,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 4,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "cosmos"
        ],
        "visibility": "private",
        "forks": 2,
        "open_issues": 4,
        "watchers": 0,
        "default_branch": "master",
        "custom_properties": {}
    },
    "organization": {
        "login": "corp",
        "id": 17,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjE3",
        "url": "https://github.netflix.net/api/v3/orgs/corp",
        "repos_url": "https://github.netflix.net/api/v3/orgs/corp/repos",
        "events_url": "https://github.netflix.net/api/v3/orgs/corp/events",
        "hooks_url": "https://github.netflix.net/api/v3/orgs/corp/hooks",
        "issues_url": "https://github.netflix.net/api/v3/orgs/corp/issues",
        "members_url": "https://github.netflix.net/api/v3/orgs/corp/members{/member}",
        "public_members_url": "https://github.netflix.net/api/v3/orgs/corp/public_members{/member}",
        "avatar_url": "https://github.netflix.net/avatars/u/17?",
        "description": ""
    },
    "enterprise": {
        "id": 1,
        "slug": "netflix",
        "name": "Netflix",
        "node_id": "MDEwOkVudGVycHJpc2Ux",
        "avatar_url": "https://github.netflix.net/avatars/b/1?",
        "description": "",
        "website_url": "",
        "html_url": "https://github.netflix.net/enterprises/netflix",
        "created_at": "2023-10-12T18:17:01Z",
        "updated_at": "2024-12-11T16:47:46Z"
    },
    "sender": {
        "login": "arcas[bot]",
        "id": 25,
        "node_id": "MDM6Qm90MjU=",
        "avatar_url": "https://github.netflix.net/avatars/in/3?",
        "gravatar_id": "",
        "url": "https://github.netflix.net/api/v3/users/arcas%5Bbot%5D",
        "html_url": "https://github.netflix.net/github-apps/arcas",
        "followers_url": "https://github.netflix.net/api/v3/users/arcas%5Bbot%5D/followers",
        "following_url": "https://github.netflix.net/api/v3/users/arcas%5Bbot%5D/following{/other_user}",
        "gists_url": "https://github.netflix.net/api/v3/users/arcas%5Bbot%5D/gists{/gist_id}",
        "starred_url": "https://github.netflix.net/api/v3/users/arcas%5Bbot%5D/starred{/owner}{/repo}",
        "subscriptions_url": "https://github.netflix.net/api/v3/users/arcas%5Bbot%5D/subscriptions",
        "organizations_url": "https://github.netflix.net/api/v3/users/arcas%5Bbot%5D/orgs",
        "repos_url": "https://github.netflix.net/api/v3/users/arcas%5Bbot%5D/repos",
        "events_url": "https://github.netflix.net/api/v3/users/arcas%5Bbot%5D/events{/privacy}",
        "received_events_url": "https://github.netflix.net/api/v3/users/arcas%5Bbot%5D/received_events",
        "type": "Bot",
        "site_admin": false
    }
}
