POST /webhooks HTTP/1.1
accept: */*
b3: 679c573afab1e2cadec6edab606381fd-326482794b8655e4-0
connection: close
content-type: application/json
host: githubhookreceiver.prod.example.net
user-agent: GitHub-Hookshot/6c41911
x-github-delivery: 47497ad0-df8f-11ef-9216-ee00af88956c
x-github-enterprise-host: github.example.com
x-github-enterprise-version: 3.13.7
x-github-event: check_run
x-github-hook-id: 2
x-github-hook-installation-target-id: 17
x-github-hook-installation-target-type: organization

{
  "enterprise": {
    "id": 1,
    "slug": "example",
    "name": "Example",
    "node_id": "MDEwOkVudGVycHJpc2Ux",
    "avatar_url": "https://github.example.com/avatars/b/1?",
    "description": "",
    "website_url": "",
    "html_url": "https://github.example.com/enterprises/example",
    "created_at": "2023-10-12T18:17:01Z",
    "updated_at": "2026-04-17T16:34:43Z"
  },
  "repository": {
    "id": 105069,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMDUwNjk=",
    "name": "example-repo",
    "full_name": "corp/example-repo",
    "private": true,
    "owner": {
      "login": "corp",
      "id": 17,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjE3",
      "avatar_url": "https://github.example.com/avatars/u/17?",
      "gravatar_id": "",
      "url": "https://github.example.com/api/v3/users/corp",
      "html_url": "https://github.example.com/corp",
      "followers_url": "https://github.example.com/api/v3/users/corp/followers",
      "following_url": "https://github.example.com/api/v3/users/corp/following{/other_user}",
      "gists_url": "https://github.example.com/api/v3/users/corp/gists{/gist_id}",
      "starred_url": "https://github.example.com/api/v3/users/corp/starred{/owner}{/repo}",
      "subscriptions_url": "https://github.example.com/api/v3/users/corp/subscriptions",
      "organizations_url": "https://github.example.com/api/v3/users/corp/orgs",
      "repos_url": "https://github.example.com/api/v3/users/corp/repos",
      "events_url": "https://github.example.com/api/v3/users/corp/events{/privacy}",
      "received_events_url": "https://github.example.com/api/v3/users/corp/received_events",
      "type": "Organization",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.example.com/corp/example-repo",
    "description": null,
    "fork": false,
    "url": "https://github.example.com/api/v3/repos/corp/example-repo",
    "forks_url": "https://github.example.com/api/v3/repos/corp/example-repo/forks",
    "keys_url": "https://github.example.com/api/v3/repos/corp/example-repo/keys{/key_id}",
    "collaborators_url": "https://github.example.com/api/v3/repos/corp/example-repo/collaborators{/collaborator}",
    "teams_url": "https://github.example.com/api/v3/repos/corp/example-repo/teams",
    "hooks_url": "https://github.example.com/api/v3/repos/corp/example-repo/hooks",
    "issue_events_url": "https://github.example.com/api/v3/repos/corp/example-repo/issues/events{/number}",
    "events_url": "https://github.example.com/api/v3/repos/corp/example-repo/events",
    "assignees_url": "https://github.example.com/api/v3/repos/corp/example-repo/assignees{/user}",
    "branches_url": "https://github.example.com/api/v3/repos/corp/example-repo/branches{/branch}",
    "tags_url": "https://github.example.com/api/v3/repos/corp/example-repo/tags",
    "blobs_url": "https://github.example.com/api/v3/repos/corp/example-repo/git/blobs{/sha}",
    "git_tags_url": "https://github.example.com/api/v3/repos/corp/example-repo/git/tags{/sha}",
    "git_refs_url": "https://github.example.com/api/v3/repos/corp/example-repo/git/refs{/sha}",
    "trees_url": "https://github.example.com/api/v3/repos/corp/example-repo/git/trees{/sha}",
    "statuses_url": "https://github.example.com/api/v3/repos/corp/example-repo/statuses/{sha}",
    "languages_url": "https://github.example.com/api/v3/repos/corp/example-repo/languages",
    "stargazers_url": "https://github.example.com/api/v3/repos/corp/example-repo/stargazers",
    "contributors_url": "https://github.example.com/api/v3/repos/corp/example-repo/contributors",
    "subscribers_url": "https://github.example.com/api/v3/repos/corp/example-repo/subscribers",
    "subscription_url": "https://github.example.com/api/v3/repos/corp/example-repo/subscription",
    "commits_url": "https://github.example.com/api/v3/repos/corp/example-repo/commits{/sha}",
    "git_commits_url": "https://github.example.com/api/v3/repos/corp/example-repo/git/commits{/sha}",
    "comments_url": "https://github.example.com/api/v3/repos/corp/example-repo/comments{/number}",
    "issue_comment_url": "https://github.example.com/api/v3/repos/corp/example-repo/issues/comments{/number}",
    "contents_url": "https://github.example.com/api/v3/repos/corp/example-repo/contents/{+path}",
    "compare_url": "https://github.example.com/api/v3/repos/corp/example-repo/compare/{base}...{head}",
    "merges_url": "https://github.example.com/api/v3/repos/corp/example-repo/merges",
    "archive_url": "https://github.example.com/api/v3/repos/corp/example-repo/{archive_format}{/ref}",
    "downloads_url": "https://github.example.com/api/v3/repos/corp/example-repo/downloads",
    "issues_url": "https://github.example.com/api/v3/repos/corp/example-repo/issues{/number}",
    "pulls_url": "https://github.example.com/api/v3/repos/corp/example-repo/pulls{/number}",
    "milestones_url": "https://github.example.com/api/v3/repos/corp/example-repo/milestones{/number}",
    "notifications_url": "https://github.example.com/api/v3/repos/corp/example-repo/notifications{?since,all,participating}",
    "labels_url": "https://github.example.com/api/v3/repos/corp/example-repo/labels{/name}",
    "releases_url": "https://github.example.com/api/v3/repos/corp/example-repo/releases{/id}",
    "deployments_url": "https://github.example.com/api/v3/repos/corp/example-repo/deployments",
    "created_at": "2025-09-23T05:06:42Z",
    "updated_at": "2026-08-14T23:09:03Z",
    "pushed_at": "2026-08-14T23:11:55Z",
    "git_url": "git://github.example.com/corp/example-repo.git",
    "ssh_url": "git@github.example.com:corp/example-repo.git",
    "clone_url": "https://github.example.com/corp/example-repo.git",
    "svn_url": "https://github.example.com/corp/example-repo",
    "homepage": null,
    "size": 14786,
    "stargazers_count": 2,
    "watchers_count": 2,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 3,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 8,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "example"
    ],
    "visibility": "private",
    "forks": 3,
    "open_issues": 8,
    "watchers": 2,
    "default_branch": "main",
    "custom_properties": {
      "arcas_managed_branch_protection_rule": "false",
      "example_pr_required": "false"
    }
  },
  "check_run": {
    "id": 19795254,
    "name": "cd / Start",
    "node_id": "MDg6Q2hlY2tSdW4xOTc5NTI1NA==",
    "head_sha": "f9355e7931d01d4d3d53cb759a5075167eeb22bf",
    "external_id": "c5ca5589-64b3-5d9c-5a0f-bbbb356e76b0",
    "url": "https://github.example.com/api/v3/repos/corp/example-repo/check-runs/19795254",
    "html_url": "https://github.example.com/corp/example-repo/actions/runs/13644/job/19795254",
    "details_url": "https://github.example.com/corp/example-repo/actions/runs/13644/job/19795254",
    "status": "waiting",
    "conclusion": null,
    "started_at": "2026-08-14T23:11:57Z",
    "completed_at": null,
    "output": {
      "title": null,
      "summary": null,
      "text": null,
      "annotations_count": 0,
      "annotations_url": "https://github.example.com/api/v3/repos/corp/example-repo/check-runs/19795254/annotations"
    },
    "check_suite": {
      "id": 197842561,
      "node_id": "MDEwOkNoZWNrU3VpdGUxOTc4NDI1NjE=",
      "head_branch": "main",
      "head_sha": "f9355e7931d01d4d3d53cb759a5075167eeb22bf",
      "status": "waiting",
      "conclusion": null,
      "url": "https://github.example.com/api/v3/repos/corp/example-repo/check-suites/197842561",
      "before": "3e0313856250708a9ecb0f01d92d69dd569d7b22",
      "after": "f9355e7931d01d4d3d53cb759a5075167eeb22bf",
      "pull_requests": [],
      "app": {
        "id": 170,
        "client_id": "f9e9c14d2c78f001af38",
        "slug": "github-actions",
        "node_id": "MDM6QXBwMTcw",
        "owner": {
          "login": "github-enterprise",
          "id": 2,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjI=",
          "avatar_url": "https://github.example.com/avatars/u/2?",
          "gravatar_id": "",
          "url": "https://github.example.com/api/v3/users/github-enterprise",
          "html_url": "https://github.example.com/github-enterprise",
          "followers_url": "https://github.example.com/api/v3/users/github-enterprise/followers",
          "following_url": "https://github.example.com/api/v3/users/github-enterprise/following{/other_user}",
          "gists_url": "https://github.example.com/api/v3/users/github-enterprise/gists{/gist_id}",
          "starred_url": "https://github.example.com/api/v3/users/github-enterprise/starred{/owner}{/repo}",
          "subscriptions_url": "https://github.example.com/api/v3/users/github-enterprise/subscriptions",
          "organizations_url": "https://github.example.com/api/v3/users/github-enterprise/orgs",
          "repos_url": "https://github.example.com/api/v3/users/github-enterprise/repos",
          "events_url": "https://github.example.com/api/v3/users/github-enterprise/events{/privacy}",
          "received_events_url": "https://github.example.com/api/v3/users/github-enterprise/received_events",
          "type": "Organization",
          "user_view_type": "public",
          "site_admin": false
        },
        "name": "GitHub Actions",
        "description": null,
        "external_url": "http://localhost:5014",
        "html_url": "https://github.example.com/github-apps/github-actions",
        "created_at": "2025-08-30T16:26:01Z",
        "updated_at": "2026-01-24T17:21:29Z",
        "permissions": {
          "actions": "write",
          "administration": "read",
          "attestations": "write",
          "checks": "write",
          "contents": "write",
          "deployments": "write",
          "discussions": "write",
          "issues": "write",
          "merge_queues": "write",
          "metadata": "read",
          "organization_packages": "write",
          "packages": "write",
          "pages": "write",
          "pull_requests": "write",
          "repository_hooks": "write",
          "repository_projects": "write",
          "security_events": "write",
          "statuses": "write",
          "vulnerability_alerts": "read"
        },
        "events": [
          "branch_protection_rule",
          "check_run",
          "check_suite",
          "create",
          "delete",
          "deployment",
          "deployment_status",
          "discussion",
          "discussion_comment",
          "fork",
          "gollum",
          "issues",
          "issue_comment",
          "label",
          "merge_group",
          "milestone",
          "page_build",
          "project",
          "project_card",
          "project_column",
          "public",
          "pull_request",
          "pull_request_review",
          "pull_request_review_comment",
          "push",
          "registry_package",
          "release",
          "repository_dispatch",
          "status",
          "watch",
          "workflow_dispatch",
          "workflow_run"
        ]
      },
      "created_at": "2026-08-14T23:11:57Z",
      "updated_at": "2026-08-14T23:11:58Z"
    },
    "app": {
      "id": 170,
      "client_id": "f9e9c14d2c78f001af38",
      "slug": "github-actions",
      "node_id": "MDM6QXBwMTcw",
      "owner": {
        "login": "github-enterprise",
        "id": 2,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjI=",
        "avatar_url": "https://github.example.com/avatars/u/2?",
        "gravatar_id": "",
        "url": "https://github.example.com/api/v3/users/github-enterprise",
        "html_url": "https://github.example.com/github-enterprise",
        "followers_url": "https://github.example.com/api/v3/users/github-enterprise/followers",
        "following_url": "https://github.example.com/api/v3/users/github-enterprise/following{/other_user}",
        "gists_url": "https://github.example.com/api/v3/users/github-enterprise/gists{/gist_id}",
        "starred_url": "https://github.example.com/api/v3/users/github-enterprise/starred{/owner}{/repo}",
        "subscriptions_url": "https://github.example.com/api/v3/users/github-enterprise/subscriptions",
        "organizations_url": "https://github.example.com/api/v3/users/github-enterprise/orgs",
        "repos_url": "https://github.example.com/api/v3/users/github-enterprise/repos",
        "events_url": "https://github.example.com/api/v3/users/github-enterprise/events{/privacy}",
        "received_events_url": "https://github.example.com/api/v3/users/github-enterprise/received_events",
        "type": "Organization",
        "user_view_type": "public",
        "site_admin": false
      },
      "name": "GitHub Actions",
      "description": null,
      "external_url": "http://localhost:5014",
      "html_url": "https://github.example.com/github-apps/github-actions",
      "created_at": "2025-08-30T16:26:01Z",
      "updated_at": "2026-01-24T17:21:29Z",
      "permissions": {
        "actions": "write",
        "administration": "read",
        "attestations": "write",
        "checks": "write",
        "contents": "write",
        "deployments": "write",
        "discussions": "write",
        "issues": "write",
        "merge_queues": "write",
        "metadata": "read",
        "organization_packages": "write",
        "packages": "write",
        "pages": "write",
        "pull_requests": "write",
        "repository_hooks": "write",
        "repository_projects": "write",
        "security_events": "write",
        "statuses": "write",
        "vulnerability_alerts": "read"
      },
      "events": [
        "branch_protection_rule",
        "check_run",
        "check_suite",
        "create",
        "delete",
        "deployment",
        "deployment_status",
        "discussion",
        "discussion_comment",
        "fork",
        "gollum",
        "issues",
        "issue_comment",
        "label",
        "merge_group",
        "milestone",
        "page_build",
        "project",
        "project_card",
        "project_column",
        "public",
        "pull_request",
        "pull_request_review",
        "pull_request_review_comment",
        "push",
        "registry_package",
        "release",
        "repository_dispatch",
        "status",
        "watch",
        "workflow_dispatch",
        "workflow_run"
      ]
    },
    "pull_requests": [],
    "deployment": {
      "url": "https://github.example.com/api/v3/repos/corp/example-repo/deployments/2812",
      "id": 2812,
      "node_id": "MDEwOkRlcGxveW1lbnQyODEy",
      "task": "deploy",
      "original_environment": "test",
      "environment": "test",
      "description": null,
      "created_at": "2026-08-14T23:11:58Z",
      "updated_at": "2026-08-14T23:11:58Z",
      "statuses_url": "https://github.example.com/api/v3/repos/corp/example-repo/deployments/2812/statuses",
      "repository_url": "https://github.example.com/api/v3/repos/corp/example-repo"
    }
  },
  "sender": {
    "login": "monalisa",
    "id": 1,
    "node_id": "MDQ6VXNlcjE=",
    "avatar_url": "https://github.example.com/avatars/u/1?",
    "gravatar_id": "",
    "url": "https://github.example.com/api/v3/users/monalisa",
    "html_url": "https://github.example.com/monalisa",
    "followers_url": "https://github.example.com/api/v3/users/monalisa/followers",
    "following_url": "https://github.example.com/api/v3/users/monalisa/following{/other_user}",
    "gists_url": "https://github.example.com/api/v3/users/monalisa/gists{/gist_id}",
    "starred_url": "https://github.example.com/api/v3/users/monalisa/starred{/owner}{/repo}",
    "subscriptions_url": "https://github.example.com/api/v3/users/monalisa/subscriptions",
    "organizations_url": "https://github.example.com/api/v3/users/monalisa/orgs",
    "repos_url": "https://github.example.com/api/v3/users/monalisa/repos",
    "events_url": "https://github.example.com/api/v3/users/monalisa/events{/privacy}",
    "received_events_url": "https://github.example.com/api/v3/users/monalisa/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "organization": {
    "login": "corp",
    "id": 17,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjE3",
    "url": "https://github.example.com/api/v3/orgs/corp",
    "repos_url": "https://github.example.com/api/v3/orgs/corp/repos",
    "events_url": "https://github.example.com/api/v3/orgs/corp/events",
    "hooks_url": "https://github.example.com/api/v3/orgs/corp/hooks",
    "issues_url": "https://github.example.com/api/v3/orgs/corp/issues",
    "members_url": "https://github.example.com/api/v3/orgs/corp/members{/member}",
    "public_members_url": "https://github.example.com/api/v3/orgs/corp/public_members{/member}",
    "avatar_url": "https://github.example.com/avatars/u/17?",
    "description": ""
  },
  "action": "created",
  "timestamp": "2026-08-14T23:11:58.575310432Z",
  "ts": 1786749118622
}
