name: Unignore Tests

on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  unignore-tests:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: 1784694
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: gradle/actions/wrapper-validation@v6

      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: zulu
          cache: gradle

      - uses: gradle/actions/setup-gradle@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Run unignore script
        run: |-
          uv run scripts/unignore.py

      - name: Check for changes
        id: check
        run: |
          if git diff --quiet; then
            echo "No changes detected"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected:"
            git diff
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        if: steps.check.outputs.changed == 'true'
        run: |-
          git checkout -b unignore-tests
          git add .
          git commit -m "Unignore tests"
          git push --force origin unignore-tests
          gh pr create --base main --fill
